id: P003164
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6982
  title: ནུབ་ཕྱོགས་ཤེར་རྟོགས་རིག་པའི་འཇུག་ངོགས།
  author: ''
  volumes:
    3dfbf89705e847e0a597bba087175937:
      image_group_id: I3CN6984
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
